modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="perodiumcraft"
version="2.0.2"
displayName="PerodiumCraft: The Next Generation"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://momentariymodder.github.io/"
updateJSONURL="https://raw.githubusercontent.com/MomentariyModder/versions/main/PerodiumCraft/version.json"
logoFile="logo.png"
authors="MomentariyModder"
description='''
A new main resource appears in the game - Perodium. It is possible to make super-tools and super-armor from it. It is not so easy to create a periodium. But you will be pleased with the result. And a new world is added.  
'''

[[dependencies.perodiumcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.perodiumcraft]]
    modId="momentariycore2"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


